apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: development
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80    # ← change this from 8080 to 80
      protocol: TCP
  type: ClusterIP
